[package]
name = "zk-fabric"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
rand = "0.9.1"
# mpz = { git = "https://github.com/privacy-scaling-explorations/mpz", branch = "dev" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"